name: screener2
base: core18
version: '0.0.1'
summary: A terminal app for take screenshot
description: |
  * take desktop
  * take area
  * dealy
  * png/jpg
grade: stable
confinement: strict

parts:

  screener2:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - click
      - pyYaml
      - pyautogui
      - pyperclip
      - imgurpython
      - Pillow
    stage-packages:
      - scrot
      - xclip

  screener2-run:
    plugin: dump
    source: scripts
    organize:
      run.sh: bin/

apps:
  screener2:
    command: bin/run.sh
    plugs:
      - home
      - network